// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_AOHmBaoL2S3QTDn-fB9YtK8uNQNxysM',
    appId: '1:78253622208:web:7d56d18f5d84a08d207e25',
    messagingSenderId: '78253622208',
    projectId: 'flutter-chat-app-fa913',
    authDomain: 'flutter-chat-app-fa913.firebaseapp.com',
    storageBucket: 'flutter-chat-app-fa913.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNyTQ0xWolzyBxRouKtSAKtGZcpNpcDg8',
    appId: '1:78253622208:android:dd94afe8ab365579207e25',
    messagingSenderId: '78253622208',
    projectId: 'flutter-chat-app-fa913',
    storageBucket: 'flutter-chat-app-fa913.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUX4ZNURUIYgDQDpN_Ak-Q61BaqiVxJOg',
    appId: '1:78253622208:ios:307505f5d37f5a00207e25',
    messagingSenderId: '78253622208',
    projectId: 'flutter-chat-app-fa913',
    storageBucket: 'flutter-chat-app-fa913.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUX4ZNURUIYgDQDpN_Ak-Q61BaqiVxJOg',
    appId: '1:78253622208:ios:307505f5d37f5a00207e25',
    messagingSenderId: '78253622208',
    projectId: 'flutter-chat-app-fa913',
    storageBucket: 'flutter-chat-app-fa913.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_AOHmBaoL2S3QTDn-fB9YtK8uNQNxysM',
    appId: '1:78253622208:web:3ecfbd7c804dc991207e25',
    messagingSenderId: '78253622208',
    projectId: 'flutter-chat-app-fa913',
    authDomain: 'flutter-chat-app-fa913.firebaseapp.com',
    storageBucket: 'flutter-chat-app-fa913.firebasestorage.app',
  );

}